PRODUCT_VERSION_MAJOR = 8
PRODUCT_VERSION_MINOR = 0

CURRENT_DEVICE=$(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)

AFTERLIFE_BUILDTYPE ?= UNOFFICIAL

AFTERLIFE_VERSION := AfterlifeOS-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CURRENT_DEVICE)-$(AFTERLIFE_BUILDTYPE)-$(shell date -u +%Y%m%d-%H%M)

# Display version
AFTERLIFE_DISPLAY_VERSION := v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# AfterlifeOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.afterlife.version=$(AFTERLIFE_VERSION) \
    ro.afterlife.display.version=$(AFTERLIFE_DISPLAY_VERSION) \
    ro.afterlife.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.afterlife.releasetype=$(AFTERLIFE_BUILDTYPE) \
    ro.modversion=$(AFTERLIFE_VERSION)